[package]
name = "crust-formats"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license-file.workspace = true

[[bin]]
name = "extract-streams"
path = "src/bin/extract_streams.rs"

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
